Feature/header-second
memx86/team-project-html-css pull request #3
Opened 2022-01-11 14:29 UTC by OlenaPatlata

2022-01-11 16:19 UTC, memx86 requested changes

2022-01-11 16:19 UTC, memx86 commented on src/partials/header.html
> +    <button type="button" class="data-modal-open burger__btn">
data-modal-open не класс, а дата атрибут, задать его нужно на кнопку "Buy now"

2022-01-11 16:19 UTC, memx86 commented on src/partials/header.html
> +        <use href="./images/sprite.svg#bracket-right"></use>
fill: transparent; уберет лишнюю заливку

2022-01-11 16:19 UTC, memx86 commented on src/partials/header.html
> +    <button type="button" class="button-buy-now">
button-buy-now мне не совсем нравится с точки зрения БЭМ. Может, просто buy-button?

2022-01-11 16:19 UTC, memx86 commented on src/partials/header.html
> +          <li><a href="#advantages" class="hero__buttons--light">How it&#39;s made?</a></li>
hero__buttons--dark hero__buttons--light это модификаторы, нужен же еще основной класс?
Может, сделать что-то вроде hero__button-light, hero__button-dark?

2022-01-11 16:19 UTC, memx86 commented on src/partials/header.html
> +      <picture classhero__img--ice>
classhero__img--ice опечатка, основной класс, модификатор?

2022-01-11 16:19 UTC, memx86 commented on src/partials/header.html
> +        <img src="./images/header/ellipse-l.png" alt="Круг розового цвета" />
в тег img мы ставим картинку для мобильных устройств, mobile-firstt

2022-01-11 16:19 UTC, memx86 commented on src/partials/header.html
> +      <picture class="hero__img--ice">
class?

2022-01-11 16:19 UTC, memx86 commented on src/partials/header.html
> +          type="image/jpeg"
type="image/png"

2022-01-11 16:19 UTC, memx86 commented on src/sass/layout/_header.scss
> +      color: var(--accent-cl);
Может, сделать выделение как раз модификатором?

2022-01-11 21:41 UTC, OlenaPatlata commented on src/partials/header.html
> +      <picture classhero__img--ice>
Да, опечатка, исправила.

2022-01-11 21:41 UTC, OlenaPatlata commented on src/partials/header.html
> +          type="image/jpeg"
Исправила

2022-01-12 09:18 UTC, OlenaPatlata commented on src/partials/header.html
>      <a class="logo link" href="" id="logo">
Убрала id

2022-01-12 09:19 UTC, OlenaPatlata commented on src/partials/header.html
> +    <button type="button" class="data-modal-open burger__btn">
Исправила

2022-01-12 09:21 UTC, OlenaPatlata commented on src/partials/header.html
> +        <use href="./images/sprite.svg#bracket-right"></use>
Пока не разобралась, оставила png.

2022-01-12 09:22 UTC, OlenaPatlata commented on src/partials/header.html
> +    <button type="button" class="button-buy-now">
Теперь  class="buy-btn header__buy-btn"

2022-01-12 09:26 UTC, OlenaPatlata commented on src/partials/header.html
> +          <li><a href="#advantages" class="hero__buttons--light">How it&#39;s made?</a></li>
исправила на  hero__button-light, hero__button-dark

2022-01-12 09:30 UTC, OlenaPatlata commented on src/partials/header.html
> +        <img src="./images/header/ellipse-l.png" alt="Круг розового цвета" />
Поменяла

2022-01-12 09:31 UTC, OlenaPatlata commented on src/partials/header.html
> +      <picture class="hero__img--ice">
Теперь class="hero__img-ice"

2022-01-12 09:31 UTC, OlenaPatlata commented on src/sass/layout/_header.scss
> +      color: var(--accent-cl);
Пока не трогала оставила как есть.

2022-01-12 13:43 UTC, memx86 approved these changes

2022-01-12 13:44 UTC, merged