Feature/review section
memx86/team-project-html-css pull request #4
Opened 2022-01-11 15:05 UTC by starvadym

Выполнена работа по пунктам 6.01 - 6.07 без подключения script слайдера в index.html.

2022-01-11 16:42 UTC, memx86 requested changes
Картинки на всех разрешениях одни и те же? 
Можно подключать скрипт в index.html?

2022-01-11 16:42 UTC, memx86 commented on src/partials/reviews.html
> +  <h1 class="visually-hidden">Reviews</h1>
не может быть h1 он только один на странице - в герое. h2

2022-01-11 16:42 UTC, memx86 commented on src/sass/layout/_reviews.scss
> +    position: relative;
Не понял зачем здесь position: relative

2022-01-11 16:42 UTC, memx86 commented on src/sass/layout/_reviews.scss
> +    background-image: url("data:image/svg+xml;charset=UTF-8,%3csvg width='32' height='4' viewBox='0 0 32 4' fill='none' xmlns='http://www.w3.org/2000/svg'%3e%3ccircle cx='16' cy='2' r='2' fill='%23C7
Мне не совсем нравится использование инлайн-свг. Спрайт мы не можем использовать, может, тогда вынесем в отдельные файлы?

2022-01-11 16:42 UTC, memx86 commented on src/partials/reviews.html
> +<section id="about-us" class="review section">
id тут не нужен на эту секцию нет якорей. (About us это секция с молоком)

2022-01-11 18:50 UTC, starvadym commented on src/sass/layout/_reviews.scss
> +    background-image: url("data:image/svg+xml;charset=UTF-8,%3csvg width='32' height='4' viewBox='0 0 32 4' fill='none' xmlns='http://www.w3.org/2000/svg'%3e%3ccircle cx='16' cy='2' r='2' fill='%23C7
Хорошо. Сделал через отдельные файлы.

2022-01-11 18:50 UTC, starvadym commented on src/sass/layout/_reviews.scss
> +    position: relative;
Да. Он просто не нужен. Уже убрал.

2022-01-11 18:50 UTC, starvadym commented on src/partials/reviews.html
> +  <h1 class="visually-hidden">Reviews</h1>
Да. Исправлено на h2.

2022-01-11 18:51 UTC, starvadym commented on src/partials/reviews.html
> +<section id="about-us" class="review section">
Уже убрал.

2022-01-11 18:55 UTC, starvadym commented on src/partials/reviews.html
> +<section id="about-us" class="review section">
Отправил в Slack скрипт на подключение слайдера.

2022-01-11 18:57 UTC, starvadym commented on src/partials/reviews.html
> +<section id="about-us" class="review section">
Да картинки все одинаковые 85x85 px. Скачал webp и jpg 1x  2x.

2022-01-12 09:11 UTC, memx86 requested changes
Оптимизировать svg

2022-01-12 09:33 UTC, starvadym commented
Да смотри три файлика svg уже отредактированы. Размеры сохраняются из-за размеров вьюпорта.

2022-01-12 09:38 UTC, memx86 approved these changes

2022-01-12 09:38 UTC, merged